// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADZBR7a3E30646Q2H2T_-xoOPbI5CwRf8',
    appId: '1:568005448678:web:35511fd6e3ec9212203c27',
    messagingSenderId: '568005448678',
    projectId: 'pizza-delivery-2d34c',
    authDomain: 'pizza-delivery-2d34c.firebaseapp.com',
    storageBucket: 'pizza-delivery-2d34c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB54d61auClbGfSl_AiVC0uAAHC3yCpLvI',
    appId: '1:568005448678:android:27db69dd24e0872c203c27',
    messagingSenderId: '568005448678',
    projectId: 'pizza-delivery-2d34c',
    storageBucket: 'pizza-delivery-2d34c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADZBR7a3E30646Q2H2T_-xoOPbI5CwRf8',
    appId: '1:568005448678:web:4aad5a95cc13e827203c27',
    messagingSenderId: '568005448678',
    projectId: 'pizza-delivery-2d34c',
    authDomain: 'pizza-delivery-2d34c.firebaseapp.com',
    storageBucket: 'pizza-delivery-2d34c.firebasestorage.app',
  );
}
